import React from 'react';
import { Link } from 'react-router-dom';
import './Legal.css';

const LegalLayout = ({ title, children }) => (
  <div className="legal-page">
    <header className="legal-nav">
      <Link to="/" className="legal-back">← Back to Plumfolio</Link>
    </header>
    <article className="legal-doc">
      <p className="legal-doc-label">Legal</p>
      <h1>{title}</h1>
      <p className="legal-updated">Last updated: June 2026</p>
      <div className="legal-body">{children}</div>
      <footer className="legal-foot">
        <span>© {new Date().getFullYear()} Futurify Designs</span>
        <nav>
          <Link to="/terms">Terms</Link>
          <Link to="/privacy">Privacy</Link>
        </nav>
      </footer>
    </article>
  </div>
);

const Terms = () => (
  <LegalLayout title="Terms & Conditions">
    <section>
      <h2>1. Agreement</h2>
      <p>
        By creating an account or using Plumfolio, you agree to these Terms. If you do not agree,
        do not use the service. Plumfolio is operated by Futurify Designs.
      </p>
    </section>
    <section>
      <h2>2. The service</h2>
      <p>
        Plumfolio is a personal finance tracking tool. It helps you record transactions, set budgets,
        view analytics, and generate reports. It is for personal use only — not for business,
        institutional, or professional financial advisory purposes.
      </p>
    </section>
    <section>
      <h2>3. Your account</h2>
      <p>
        You must provide accurate information when registering. You are responsible for keeping
        your password confidential and for all activity under your account. Notify us promptly if
        you suspect unauthorised access.
      </p>
    </section>
    <section>
      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use Plumfolio for any unlawful purpose</li>
        <li>Attempt to access other users&apos; data or compromise the platform</li>
        <li>Upload malicious code or interfere with the service</li>
        <li>Resell or redistribute the service without permission</li>
      </ul>
    </section>
    <section>
      <h2>5. Your data</h2>
      <p>
        You retain ownership of the financial data you enter. We process it only to provide the
        service, as described in our <Link to="/privacy">Privacy Policy</Link>. You may delete
        your account and associated data from Settings at any time.
      </p>
    </section>
    <section>
      <h2>6. Not financial advice</h2>
      <p>
        Plumfolio displays calculations, forecasts, and insights based on data you provide. These
        are informational only and do not constitute financial, tax, or investment advice. Always
        consult a qualified professional for important financial decisions.
      </p>
    </section>
    <section>
      <h2>7. Availability &amp; changes</h2>
      <p>
        We aim to keep Plumfolio available but do not guarantee uninterrupted access. We may update,
        suspend, or discontinue features with reasonable notice where possible. We may revise these
        Terms; continued use after changes constitutes acceptance.
      </p>
    </section>
    <section>
      <h2>8. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, Futurify Designs is not liable for indirect,
        incidental, or consequential damages arising from your use of Plumfolio, including loss
        of data or financial loss based on forecasts or reports generated by the app.
      </p>
    </section>
    <section>
      <h2>9. Contact</h2>
      <p>
        Questions about these Terms: contact Futurify Designs through the support channels
        provided in the app or on the Plumfolio website.
      </p>
    </section>
  </LegalLayout>
);

export default Terms;
